on:
  pull_request:
  push:
    branches:
      - akou-test    # Your default branch
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: semgrep/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
